AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
