require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/simple_form.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/initializers/simple_form.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Lambda:
  Enabled: false
