env:
  global:
    - CC_TEST_REPORTER_ID=43e9fdf4ba622920860481ee6074963200787075d4ba876ea760cfb95f203480
language: ruby
cache:
  bundler: true
  yarn: true
  npm: true
rvm:
  - 2.6.5
services:
  - postgresql
addons:
  chrome: stable
before_install:
  - "gem update --system"
  - "gem install bundler"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - "bin/yarn"
script:
  - "bin/test"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


